name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Install Node Version
        uses: actions/setup-node@v4.0.4
        with:
          node-version-file: ".nvmrc"

      - name: Install Yarn
        run: npm install -g yarn@1.22.22

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn release
